#' activity aggregatio
#'
#' @description aggregates the activity classification to user specified intervalls of "avalue" minutes by using the class with max entries (mode) in interval
#'
#'
#' @author Jannis Gottwald
#'
#' @param animal list, list generated by initAnimal function
#' @param avalue numeric, aggregation interval in minutes
#' @param tzone string, Timezone of time data
#'
#' @export
#'
#'






activity.aggregate.tRackIT<-function(animal, avalue, tzone){
  
  
  Mode <- function(x) {
    ux <- unique(x)
    ux<-ux[!is.na(ux)]
    ux[which.max(tabulate(match(x, ux)))]
  }
  
  
  #list files per id and get data
  fls<-list.files(animal$path$classification, full.names = TRUE, pattern="class")
  data<-plyr::ldply(fls,function(x){data.table::fread(x)})
  
  #aggregate do 1 Minute bins 
  df<- aggregate(prediction ~ cut(timestamp, breaks = paste0(avalue, " mins")), data, Mode)
  colnames(df)<-c("timestamp", "prediction")
  
  df$timestamp<-as.POSIXct(df$timestamp, tz=tzone)
  
  #df$ID<-basename(animal$meta$animalID)
  
  data.table::fwrite(df, paste0(animal$path$classification, animal$meta$animalID, "_aggregated_", avalue,"_Minute.csv"))
  
}



Mode <- function(x) {
  ux <- unique(x)
  ux<-ux[!is.na(ux)]
  ux[which.max(tabulate(match(x, ux)))]
}
