#' activity classification
#'
#' @description classifies data based on ML variables
#'
#'
#' @author Jannis Gottwald
#'
#' @param animal list, list generated by initAnimal functiom
#'
#' @export
#'
#'




activity.predict.tRackIT<-function(animal){
  
  require(caret)
  require(randomForest)
  require(dplyr)
  
  
  mod_rec_1=readRDS(system.file("extdata", "m_r1.rds", package="tRackIT"))
  
  mod_rec_2= readRDS(system.file("extdata", "m_r2.rds", package="tRackIT"))
  
  #navigate to individuals folder in tRackIT-Project
  
  #load models

  
  fls<-list.files(animal$path$vars, full.names = TRUE)
  
  data<-plyr::ldply(fls, function(x){
    data.table::fread(x)
  })
  
  names(data)[names(data) == 'Name'] <- 'station'
  
  #predict data using model trained for 1 receiver
  data_1<-data[data$n_receivers==1,]
  data_1<-as.data.frame(data_1)
  data_1<-data_1[, c("timestamp", "station", "receiver", "max","n_receivers", mod_rec_1$selectedvars)]
 
  data_1[, mod_rec_1$selectedvars]<-sapply(data_1[, mod_rec_1$selectedvars], as.numeric)
  
  data_1<-data_1[complete.cases(data_1),]
  
  data_1<-data_1 %>% 
    filter_if(~is.numeric(.), all_vars(!is.infinite(.)))
 
  
  if(nrow(data_1)>=50){
    pred1<-predict.train(mod_rec_1, data_1)
    data_1$prediction<-pred1
    data_1<-data_1[, c("timestamp", "station", "receiver", "max","n_receivers","prediction")]
  }else{data_1<-data.frame()}
  
  
  #predict data using model trained for 2 receivers
  data_2<-data[data$n_receivers==2,]
  data_2<-as.data.frame(data_2)
  data_2<-data_2[, c("timestamp", "station", "receiver", "max","n_receivers", mod_rec_2$selectedvars)]
  data_2[, mod_rec_2$selectedvars]<-sapply(data_2[, mod_rec_2$selectedvars], as.numeric)
  data_2<-data_2[complete.cases(data_2),]
  
  data_2<-data_2 %>% 
    filter_if(~is.numeric(.), all_vars(!is.infinite(.)))
  
  
if(nrow(data_2)>=50){
    pred2<-predict(mod_rec_2, data_2)
    data_2$prediction<-pred2
    data_2<-data_2[, c("timestamp", "station", "receiver", "max","n_receivers","prediction")]
  }else{data_2<-data.frame()}
  
  
  
  #combine data and store in results folder
  data_predicted<- rbind(data_1,data_2 )
  
  data.table::fwrite(data_predicted, paste0(animal$path$classification, animal$meta$animalID, "_classified.csv"))
  
}

