#' filter automatic (tRackIT.OS)
#' @description automatic filtering of awk filtered data (only based on tRackIT.OS). Awk files may miss colnames. make shure they have colnames(data)="timestamp", "samples", "duration", "signal_freq", "signal_bw", "max_signal","noise", "receiver", "station"
#'
#'
#' @author Jannis Gottwald
#'
#'
#' 
#' @param animal list, generated by initanimal function
#' @param projList list, generatet by initProject function
#' @param path_to_data string, path to awk filtered file
#' @param freq_er numeric, accepted deviation from tag frequency
#' @param d_min numeric, minimum duration of signal
#' @param d_max numeric, maximum duration of signal
#'
#' @export
#'
#'





filter.tRackIT<-function(projList, animal, freq_er=2, path_to_data, d_min, d_max){
  
  
  fls<-list.files(path_to_data, full.names = TRUE)
  
  lapply(fls, function(f){
  
  stat<-data.table::fread(f)
  
  stat<-stat[!is.na(stat$V1),]
  stat<-as.data.frame(stat)
  stat<-stat[, colSums(is.na(stat)) != nrow(stat)]
 
  
  colnames(stat)<-c("receiver", "timestamp", "frequency", "duration", "avg", "max", "sd", "noise", "snr", "station")
  
  
  stat<-stat[!is.na(stat$timestamp),]
  stat$sig_diff<-abs(stat$frequency-as.numeric(animal$meta$freq))
  stat<-stat[stat$sig_diff<=freq_er,]
  
  stat<-stat[stat$duration>=d_min & stat$duration<=d_max,]
  
  if(nrow(stat)>=10){
  data.table::fwrite(stat, paste0(animal$path$filtered, "/",gsub(".csv","",basename(f)),"_filtered.csv"))}
  
  })
  
}
  
    
    
  










